ServerPath: D:\Codes\Multiagent\FinalProjectV4\Multiagent\Warmup\server.jar
LevelsDir: D:\Codes\Multiagent\FinalProjectV4\Multiagent\complevels-2026
BenchmarkFolder: D:\Codes\Multiagent\FinalProjectV4\Multiagent\Warmup\searchclient_python\benchmarks
ClientCommand: D:\Python310\python.exe -m searchclient.searchclient --max-memory 10240
Timeout: 180
