ServerPath: D:\Codes\Multiagent\FinalProjectV3\Multiagent\Warmup\server.jar
LevelsDir: D:\Codes\Multiagent\FinalProjectV3\Multiagent\Warmup\complevels
BenchmarkFolder: D:\Codes\Multiagent\FinalProjectV3\Multiagent\Warmup\searchclient_python\benchmarks
ClientCommand: python -m searchclient.searchclient --max-memory 10240
Timeout: 180
